version: '3'
services:
  redis:
    image: "redis:latest"
    container_name: redis-service
    ports:
      - "6379:6379"

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_REDIS_HOST: redis
    depends_on:
      - redis