package com.example.enums;

public enum States {
    ACTIVE,
    WAITING_DIRECTORY_NAME_ADD,
    WAITING_DIRECTORY_NAME_DELETE_IMPLEMENTATION,
    WAITING_DIRECTORY_NAME_CHOOSE_IMPLEMENTATION,
    WAITING_FILE_NAME,
    WAITING_FILE_NAME_ADD,
    WAITING_FILE_NAME_DOWNLOAD_IMPLEMENTATION,
    WAITING_FILE_NAME_DELETE_IMPLEMENTATION,
    WAITING_FILE_NAME_FOR_MOVING_IMPLEMENTATION,
    WAITING_DIRECTORY_NAME_FOR_MOVING_IMPLEMENTATION,
    WAITING_FILE_NAME_FOR_CHANGE_IMPLEMENTATION,
}