package com.example.enums;

public enum States {
    ACTIVE,
    WAITING_FILE,
    WAITING_FILE_NAME_CHOOSE,
    WAITING_DIRECTORY_NAME_ADD,
    WAITING_DIRECTORY_NAME_DELETE,
    WAITING_DIRECTORY_NAME_CHOOSE,
}