package com.example.enums;

public enum States {
    ACTIVE,
    CONVERT,
    WAITING_DIRECTORY_NAME_ADD,
    WAITING_DIRECTORY_NAME_DELETE,
    WAITING_DIRECTORY_NAME_CHOOSE,
    WAITING_FILE_NAME,
    WAITING_FILE_NAME_ADD,
    WAITING_FILE_NAME_DOWNLOAD,
    WAITING_FILE_NAME_DELETE,
    WAITING_FILE_NAME_FOR_CHOOSE,
    WAITING_FILE_NAME_FOR_CHANGE,
    WAITING_DIRECTORY_NAME_FOR_CHANGE
}